apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: aparasar/customer-service:latest
          ports:
            - containerPort: 5554
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  type: NodePort
  selector:
    app: customer     # ✅ fixed this line
  ports:
    - port: 5554
      targetPort: 5554
      nodePort: 30002
